"""add events table

Revision ID: 83803d5f1bd5
Revises: 64a5ffe5dbdb
Create Date: 2026-06-18 16:34:08.453403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83803d5f1bd5'
down_revision: Union[str, None] = '64a5ffe5dbdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue_public_id', sa.Uuid(), nullable=False),
    sa.Column('organizer_public_id', sa.Uuid(), nullable=False),
    sa.Column('category_public_id', sa.Uuid(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('cast_members', sa.Text(), nullable=True),
    sa.Column('speaker', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_category_public_id'), 'events', ['category_public_id'], unique=False)
    op.create_index(op.f('ix_events_city'), 'events', ['city'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_organizer_public_id'), 'events', ['organizer_public_id'], unique=False)
    op.create_index(op.f('ix_events_public_id'), 'events', ['public_id'], unique=True)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_venue_public_id'), 'events', ['venue_public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_venue_public_id'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_public_id'), table_name='events')
    op.drop_index(op.f('ix_events_organizer_public_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_city'), table_name='events')
    op.drop_index(op.f('ix_events_category_public_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###